# Generated by Django 4.1 on 2022-08-22 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase_Estrella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase_estrella', models.CharField(choices=[('O', '≥ 33000 K'), ('B', '10000–33000 K'), ('A', '7500–10000 K'), ('F', '6000–7500 K'), ('G', '5200–6000 K'), ('K', '3700–5200 K'), ('M', '≤ 3700 K')], max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Estrella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('temperatura_media', models.IntegerField()),
                ('clase_estrella', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='AppSpace.clase_estrella')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Planeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_planeta', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SistemaEstrella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('cant_estrellas', models.IntegerField()),
                ('cant_planetas', models.IntegerField()),
                ('clase_estrella', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSpace.clase_estrella')),
            ],
        ),
        migrations.CreateModel(
            name='Planeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('regiones', models.IntegerField()),
                ('habitantes', models.IntegerField()),
                ('satelites_naturales', models.IntegerField()),
                ('satelites_artificiales', models.IntegerField()),
                ('temperatura_media', models.FloatField()),
                ('estrella', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSpace.estrella')),
                ('sistema_estrella', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSpace.sistemaestrella')),
                ('tipo_planeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSpace.tipo_planeta')),
            ],
        ),
        migrations.CreateModel(
            name='Habitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('idioma', models.CharField(max_length=40, null=True)),
                ('habitando_planeta', models.CharField(max_length=40)),
                ('planeta_natal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSpace.planeta')),
            ],
        ),
        migrations.AddField(
            model_name='estrella',
            name='sistema_estrella',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSpace.sistemaestrella'),
        ),
    ]
