# Generated by Django 4.1 on 2022-08-25 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase_Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ClaseEstrella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase_estrella', models.CharField(choices=[('1', 'O'), ('2', 'B'), ('3', 'A'), ('4', 'F'), ('5', 'G'), ('6', 'K'), ('7', 'M')], max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ClasePlaneta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase_planeta', models.CharField(max_length=50)),
                ('grupo_planeta', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Estrella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('temperatura_media', models.IntegerField()),
                ('clase_estrella', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='AppSpace.claseestrella')),
            ],
        ),
        migrations.CreateModel(
            name='SistemaPlanetario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('cant_estrellas', models.IntegerField()),
                ('cant_planetas', models.IntegerField()),
                ('clase_estrella', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSpace.claseestrella')),
            ],
        ),
        migrations.CreateModel(
            name='Planeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('regiones', models.IntegerField()),
                ('habitantes', models.IntegerField()),
                ('satelites_naturales', models.IntegerField()),
                ('satelites_artificiales', models.IntegerField()),
                ('temperatura_media', models.FloatField()),
                ('clase_planeta', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AppSpace.claseplaneta')),
                ('estrella', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSpace.estrella')),
                ('sistema_planetario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSpace.sistemaplanetario')),
            ],
        ),
        migrations.CreateModel(
            name='Habitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('idioma', models.CharField(max_length=40, null=True)),
                ('habitando_planeta', models.CharField(max_length=40)),
                ('planeta_natal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSpace.planeta')),
            ],
        ),
        migrations.AddField(
            model_name='estrella',
            name='sistema_planetario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSpace.sistemaplanetario'),
        ),
    ]
