# Generated by Django 4.1 on 2022-09-19 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseEstrella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase_estrella', models.CharField(max_length=2)),
                ('temperatura', models.CharField(default='0', max_length=50)),
                ('color', models.CharField(default='color', max_length=50)),
            ],
            options={
                'db_table': 'appspace_claseestrella',
            },
        ),
        migrations.CreateModel(
            name='ClasePlaneta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase_planeta', models.CharField(max_length=50)),
                ('grupo_planeta', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'appspace_claseplaneta',
            },
        ),
        migrations.CreateModel(
            name='ClaseRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase_region', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'appspace_claseregion',
            },
        ),
        migrations.CreateModel(
            name='Estrella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('temperatura_media', models.IntegerField()),
                ('clase_estrella', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='AppSpace.claseestrella')),
            ],
            options={
                'db_table': 'appspace_estrella',
            },
        ),
        migrations.CreateModel(
            name='SistemaPlanetario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('cant_estrellas', models.IntegerField()),
                ('cant_planetas', models.IntegerField()),
                ('clase_estrella', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSpace.claseestrella')),
            ],
            options={
                'db_table': 'appspace_sistemaplanetario',
            },
        ),
        migrations.CreateModel(
            name='Planeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('regiones', models.IntegerField()),
                ('habitantes', models.IntegerField()),
                ('satelites_naturales', models.IntegerField()),
                ('satelites_artificiales', models.IntegerField()),
                ('temperatura_media', models.FloatField()),
                ('clase_planeta', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AppSpace.claseplaneta')),
                ('estrella', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSpace.estrella')),
                ('sistema_planetario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSpace.sistemaplanetario')),
            ],
            options={
                'db_table': 'appspace_planeta',
            },
        ),
        migrations.CreateModel(
            name='Habitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('idioma', models.CharField(max_length=40, null=True)),
                ('habitando_planeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_habitando_planeta', to='AppSpace.planeta')),
                ('planeta_natal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_planeta_natal', to='AppSpace.planeta')),
            ],
            options={
                'db_table': 'appspace_habitante',
            },
        ),
        migrations.AddField(
            model_name='estrella',
            name='sistema_planetario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSpace.sistemaplanetario'),
        ),
    ]
