# Generated by Django 4.1 on 2022-09-18 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSpace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estrella',
            table='appspace_estrella',
        ),
        migrations.AlterModelTable(
            name='habitante',
            table='appspace_habitante',
        ),
        migrations.AlterModelTable(
            name='planeta',
            table='appspace_planeta',
        ),
        migrations.AlterModelTable(
            name='sistemaplanetario',
            table='appspace_sistemaplanetario',
        ),
    ]
