# Generated by Django 4.1 on 2022-08-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSpace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase_region', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Clase_Region',
        ),
        migrations.RemoveField(
            model_name='claseestrella',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='claseestrella',
            name='color',
            field=models.CharField(default='color', max_length=50),
        ),
        migrations.AddField(
            model_name='claseestrella',
            name='temperatura',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='claseestrella',
            name='clase_estrella',
            field=models.CharField(max_length=2),
        ),
    ]
