# Generated by Django 4.1 on 2022-08-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSpace', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SistemaEstrella',
            new_name='SistemaPlanetario',
        ),
        migrations.RenameField(
            model_name='estrella',
            old_name='sistema_estrella',
            new_name='sistema_planetario',
        ),
        migrations.RenameField(
            model_name='planeta',
            old_name='sistema_estrella',
            new_name='sistema_planetario',
        ),
        migrations.AlterField(
            model_name='clase_estrella',
            name='clase_estrella',
            field=models.CharField(choices=[('1', 'O'), ('2', 'B'), ('3', 'A'), ('4', 'F'), ('5', 'G'), ('6', 'K'), ('7', 'M')], max_length=100),
        ),
    ]
