# Generated by Django 4.1 on 2022-08-22 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSpace', '0002_rename_sistemaestrella_sistemaplanetario_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clase_Estrella',
            new_name='ClaseEstrella',
        ),
    ]
