# Generated by Django 4.1 on 2022-09-18 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSpace', '0002_alter_estrella_table_alter_habitante_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='claseestrella',
            table='appspace_claseestrella',
        ),
        migrations.AlterModelTable(
            name='claseplaneta',
            table='appspace_claseplaneta',
        ),
        migrations.AlterModelTable(
            name='claseregion',
            table='appspace_claseregion',
        ),
    ]
