# Generated by Django 4.1 on 2022-08-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSpace', '0002_claseregion_delete_clase_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claseplaneta',
            name='descripcion',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='claseregion',
            name='descripcion',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
