# Generated by Django 4.1 on 2022-09-20 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppSpace', '0003_alter_habitante_habitando_planeta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitante',
            name='habitando_planeta',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_habitando_planeta', to='AppSpace.planeta'),
        ),
        migrations.AlterField(
            model_name='habitante',
            name='planeta_natal',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_planeta_natal', to='AppSpace.planeta'),
        ),
    ]
