# Generated by Django 4.1 on 2022-08-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSpace', '0003_rename_clase_estrella_claseestrella'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_planeta',
            name='tipo_planeta',
            field=models.CharField(choices=[('1', 'Planeta Terrestre'), ('2', 'Planeta Gaseoso'), ('3', 'Planeta Enano'), ('4', 'Otros')], max_length=50),
        ),
    ]
