# Generated by Django 4.1 on 2022-08-22 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSpace', '0004_alter_tipo_planeta_tipo_planeta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tipo_Planeta',
            new_name='TipoPlaneta',
        ),
    ]
