# Generated by Django 4.1 on 2022-09-18 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserSpace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='avatar',
            table='userspace_avatar',
        ),
    ]
