# Generated by Django 4.1 on 2022-09-19 01:24

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('UserSpace', '0002_alter_avatar_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
